name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  call-reusable-test:
    uses: ./.github/workflows/reusable-test.yml
  deploy:
    runs-on: ubuntu-latest
    environment: publish
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: '**/setup.py'
    - name: Install build/push dependencies
      run: |
        pip install setuptools wheel twine build
    - name: Publish to Test PyPi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m build
        twine upload --repository testpypi dist/*
