name: Reusable Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: '**/setup.py'
    - name: Install dependencies
      run: |
        pip install -r requirements-ci.txt
        pip install -e .
    - name: Style checks
      run: |
        isort .
        black .
        flake8 .
    - name: Download and extract test data
      run: |
        wget 'https://f000.backblazeb2.com/file/KerhinPublicBucket/qoi_test_images.zip'
        unzip qoi_test_images.zip
    - name: Run tests, even slow ones
      run: |
        pytest --run-slow
